version: "3"

services:

  runtime-setup:
    image: swift-distributed-tracing:24.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-noble"

  test:
    image: swift-distributed-tracing:24.04-main
    environment:
      - FORCE_TEST_DISCOVERY=--enable-test-discovery
      - STRICT_CONCURRENCY_ARG=-Xswiftc -strict-concurrency=complete

  shell:
    image: swift-distributed-tracing:24.04-main
